In [5]:
import pandas as pd
from bioinfokit import analys, visuz

In [4]:
df.head()

          GeneNames  value1  value2    log2FC       p-value
0  LOC_Os09g01000.1    8862   32767 -1.886539  1.250000e-55
1  LOC_Os12g42876.1    1099     117  3.231611  1.050000e-55
2  LOC_Os12g42884.2     797      88  3.179004  2.590000e-54
3  LOC_Os03g16920.1     274       7  5.290677  4.690000e-54
4  LOC_Os05g47540.4     308      18  4.096862  2.190000e-54

In [27]:
df = pd.read_csv('/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_known/up_down_known_DESEQ_6d_with_names.csv')

In [23]:
df.head()

,name,ID,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,MC_6d_1,MC_6d_2,MC_6d_3,padj,log2FoldChange,pvalue,foldChange,log10padj,id
0,Vax2os1_3,TRINITY_DN100157_c0_g1_i2,32.120287,52.452129,40.819397,22.402028,0.000000,0.000000,0.000000,4.439354e-11,-7.878068,3.290878e-12,0.004251,10.352680,RF02272
1,KCNQ1OT1_1,TRINITY_DN102574_c4_g1_i2,22.151922,20.569462,52.158118,12.801159,0.000000,0.000000,0.000000,3.197232e-07,-7.419111,4.212439e-08,0.005843,6.495226,RF01946
2,RFPL3-AS1_1,TRINITY_DN103080_c3_g1_i1,333.386424,267.403008,315.216455,361.632740,84.904988,75.180968,110.894830,2.852785e-09,-1.821005,2.744051e-10,0.283024,8.544731,RF02171
3,WT1-AS_8,TRINITY_DN103604_c5_g6_i1,90.822880,29.825720,22.677443,92.808402,3.430505,0.000000,7.392989,1.916375e-04,-4.020868,4.384025e-05,0.061602,3.717519,RF02210
4,DLG2-AS1_1,TRINITY_DN103697_c4_g4_i1,99.683648,172.783482,150.804995,211.219122,491.419781,499.732314,313.791297,1.840174e-04,1.454738,4.190373e-05,2.741067,3.735141,RF02112

In [34]:
visuz.gene_exp.volcano(d=df, lfc='log2FoldChange', pv='padj', geneid='name', genenames=("MALAT1", "HOTAIR_1", "HOTTIP_2", "HULC"), gstyle=2, valpha=0.5)