In [1]:
import pandas as pd

In [2]:
path='/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/noncoding_novel/RNAhybrid_PB/'

In [3]:
output = pd.read_csv(path+'output.csv')

In [4]:
output.head()

,query,query_len,mirna,mirna_len,MFE,pval,position_in_target,line1,line2,line3,line4
0,TRINITY_DN111675_c5_g3_i1,1289,hsa-miR-92b-3p,22,-27.3,1.0,232,A CU UCAAA U A,GGGCC GG GC AGUGCAAUA,UCCGG CC UG UCACGUUAU,CC C C
1,TRINITY_DN100028_c5_g1_i1,802,hsa-miR-92b-3p,22,-24.4,1.0,594,U UUUAA C C C,GGCC GG C AGUGCAAU,CCGG CC G UCACGUUA,CCU C U C U
2,TRINITY_DN79764_c9_g5_i1,313,hsa-miR-92b-3p,22,-28.4,1.0,162,U A CUCUCAAU G,GGUC GGAUG GGUGCAAUG,CCGG CCUGC UCACGUUAU,CCU C
3,TRINITY_DN84497_c2_g1_i2,582,hsa-miR-92b-3p,22,-22.2,1.0,432,A AUAC U,GGGA GGUGCAAU,CCCU UCACGUUA,CCUCCGG GC U
4,TRINITY_DN89285_c4_g1_i2,391,hsa-miR-92b-3p,22,-21.3,1.0,133,U U UUAAUCAUUUU G,GGCUG G GUGCAAUA,CCGGC C CACGUUAU,CCU C UGCU

In [5]:
utr = pd.read_csv(path+'mRNA_UTR_PROTEINS_merged_edited_copy.csv')

In [6]:
utr.head()

,query,Protein names_UTR,XP_01
0,TRINITY_DN100005_c7_g2_i1,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",XP_014068145.1
1,TRINITY_DN81030_c8_g4_i1,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",XP_014068145.1
2,TRINITY_DN83202_c8_g4_i2,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",XP_014068145.1
3,TRINITY_DN105298_c5_g1_i2,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",XP_014068145.1
4,TRINITY_DN91961_c5_g1_i1,"alpha-N-acetylgalactosaminide alpha-2,6-sialyl...",XP_014068145.1

In [7]:
merged = output.merge(utr, on='query')

In [8]:
merged.to_csv(path+'output_merged.csv', index=False)

In [16]:
# merge with MCLR deseq2 results

In [19]:
deseq_d1 = pd.read_csv(path+'novel_deseq_results_d1_w_names.csv')
deseq_d6 = pd.read_csv(path+'novel_deseq_results_d6_w_names.csv')
deseq_d9 = pd.read_csv(path+'novel_deseq_results_d9_w_names.csv')

In [20]:
merged_w_deseq_d1 = merged.merge(deseq_d1, on='query')

In [23]:
merged_w_deseq_d1.to_csv(path+'deseq_1d_rnahybrid_output_w_names.csv', index=False)

In [22]:
merged_w_deseq_d6 = merged.merge(deseq_d6, on='query')

In [24]:
merged_w_deseq_d6.to_csv(path+'deseq_6d_rnahybrid_output_w_names.csv', index=False)

In [25]:
merged_w_deseq_d9 = merged.merge(deseq_d9, on='query')

In [26]:
merged_w_deseq_d9.to_csv(path+'deseq_9d_rnahybrid_output_w_names.csv', index=False)

In [27]:
# merge with MIS vs MIM deseq2 results on XP_01

In [9]:
mismim1d = pd.read_csv(path+'MIM_deseq/1d_MIS_vs_MIM_DESEQ_annotated.csv', low_memory=False)

In [10]:
mismim1d.head()

,query,ident_uniprot,MIS_1d_1,MIS_1d_2,MIS_1d_3,MIM_1d_1,MIM_1d_2,MIM_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01
0,TRINITY_DN100000_c5_g1_i6,CAPON_MOUSE,683,674,487,332,561,588,539.059009,0.026450,0.302506,0.087436,0.930325,0.99999,XP_013978521.1
1,TRINITY_DN100000_c9_g1_i1,CH049_HUMAN,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,TRINITY_DN100001_c2_g2_i2,CIO1B_SALSA,1190,1280,1223,1330,962,1226,1204.694469,-0.283106,0.305356,-0.927132,0.353858,0.99999,XP_014027367.1
3,TRINITY_DN100001_c2_g2_i7,CIO1B_SALSA,451,464,516,518,434,368,458.240789,-0.232912,0.316372,-0.736197,0.461611,0.99999,XP_014015694.1
4,TRINITY_DN100001_c2_g3_i3,CIO1B_SALSA,547,568,579,466,487,429,505.126771,-0.036150,0.260897,-0.138559,0.889798,0.99999,XP_014027367.1

In [11]:
merged_mim1d = merged.merge(mismim1d, on='XP_01')

In [12]:
merged_mim1d.to_csv(path+'deseq_MIM_1d_rnahybrid_output_w_names.csv', index=False)

In [14]:
mismim6d = pd.read_csv(path+'MIM_deseq/6d_MIS_vs_MIM_DESEQ_annotated.csv', low_memory=False)

In [15]:
mismim6d.head()

,query,ident_uniprot,MIS_6d_1,MIS_6d_2,MIS_6d_3,MIM_6d_1,MIM_6d_2,MIM_6d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01
0,TRINITY_DN100000_c5_g1_i6,CAPON_MOUSE,461,313,373,643,455,423,435.965642,-0.164060,0.348457,-0.470820,0.637769,0.999906,XP_013978521.1
1,TRINITY_DN100000_c9_g1_i1,CH049_HUMAN,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,TRINITY_DN100001_c2_g2_i2,CIO1B_SALSA,1286,1440,947,1267,1339,980,1191.567772,0.237441,0.293703,0.808438,0.418838,0.999906,XP_014027367.1
3,TRINITY_DN100001_c2_g2_i7,CIO1B_SALSA,355,433,368,328,348,340,359.435656,0.386872,0.282533,1.369299,0.170906,0.999906,XP_014015694.1
4,TRINITY_DN100001_c2_g3_i3,CIO1B_SALSA,429,587,379,393,395,417,428.426882,0.399730,0.292712,1.365611,0.172061,0.999906,XP_014027367.1

In [16]:
merged_mim6d = merged.merge(mismim6d, on='XP_01')

In [17]:
merged_mim6d.to_csv(path+'deseq_MIM_6d_rnahybrid_output_w_names.csv', index=False)

In [22]:
mismim8d = pd.read_csv(path+'MIM_deseq/8d_MIS_vs_MIM_DESEQ_annotated.csv', low_memory=False)

In [23]:
mismim8d.head()

,query,ident_uniprot,MIS_8d_1,MIS_8d_2,MIS_8d_3,MIM_8d_1,MIM_8d_2,MIM_8d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,XP_01
0,TRINITY_DN100000_c5_g1_i6,CAPON_MOUSE,413,554,634,415,556,253,453.488632,0.213960,0.314849,0.679564,0.496780,0.999971,XP_013978521.1
1,TRINITY_DN100000_c9_g1_i1,CH049_HUMAN,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,TRINITY_DN100001_c2_g2_i2,CIO1B_SALSA,1019,1089,1135,940,1042,1237,1066.823351,-0.183666,0.266745,-0.688546,0.491109,0.999971,XP_014027367.1
3,TRINITY_DN100001_c2_g2_i7,CIO1B_SALSA,309,394,412,243,290,280,312.751830,0.261589,0.261880,0.998889,0.317849,0.999971,XP_014015694.1
4,TRINITY_DN100001_c2_g3_i3,CIO1B_SALSA,382,375,456,275,364,350,359.009621,0.112693,0.265376,0.424654,0.671089,0.999971,XP_014027367.1

In [24]:
merged_mim8d = merged.merge(mismim8d, on='XP_01')

In [25]:
merged_mim8d.to_csv(path+'deseq_MIM_8d_rnahybrid_output_w_names.csv', index=False)