In [1]:
import pandas as pd

In [23]:
path='/mnt/sdb1/Project_Sieja_MCLR_52/1_code/'

In [24]:
uniprot = pd.read_csv(path+"proteins.headers")
uniprot.columns=['trinity']
uniprot.shape

(125838, 1)

In [25]:
salmo = pd.read_csv(path+"protein_salmo.headers")
salmo.columns=['trinity']
salmo.shape

(148645, 1)

In [31]:
uniprot_salmo = uniprot['trinity'].append(salmo['trinity'])

In [33]:
uniprot_salmo.drop_duplicates(inplace=True)

In [34]:
uniprot_salmo.shape

(170757,)

In [38]:
uniprot_salmo.to_csv(path+'protein_uniprot_salmo_combined.headers', index=False)

In [1]:
# combine uniprot and salmo annotation report with deseq results

In [2]:
path="/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/"

In [10]:
annot_report = pd.read_csv(path+'report_salmo_annot_feature_map_uniprot_and_salmo_proteins.csv', sep='\t')
annot_report.head()

,trinity,ident_uniprot,ident_salmo
0,TRINITY_DN100000_c5_g1,CAPON_HUMAN^CAPON_MOUSE,XP_013978521.1^XP_014024532.1
1,TRINITY_DN100000_c5_g1_i2,CAPON_HUMAN,XP_014024532.1
2,TRINITY_DN100000_c5_g1_i6,CAPON_MOUSE,XP_013978521.1
3,TRINITY_DN100000_c9_g1,CH049_HUMAN,NaN
4,TRINITY_DN100000_c9_g1_i1,CH049_HUMAN,NaN

In [9]:
deseq_results = pd.read_csv(path+"1d_MIS_vs_INH_DESEQ.csv")
deseq_results.head()

,trinity,MIS_1d_1,MIS_1d_2,MIS_1d_3,INH_1d_1,INH_1d_2,INH_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN100000_c5_g1_i6,683,674,487,685,654,492,604.304316,-0.179745,0.304724,-0.589861,0.555284,0.999996
1,TRINITY_DN100000_c9_g1_i1,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN
2,TRINITY_DN100001_c2_g2_i2,1190,1280,1223,1034,1012,1252,1145.939552,-0.035965,0.256702,-0.140103,0.888579,0.999996
3,TRINITY_DN100001_c2_g2_i7,451,464,516,377,338,305,398.258863,0.292943,0.267341,1.095766,0.273181,0.999996
4,TRINITY_DN100001_c2_g3_i3,547,568,579,522,338,320,466.619820,0.327023,0.311017,1.051464,0.293046,0.999996

In [11]:
merged = deseq_results.merge(annot_report, on='trinity')

In [12]:
merged.head()

,trinity,MIS_1d_1,MIS_1d_2,MIS_1d_3,INH_1d_1,INH_1d_2,INH_1d_3,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,ident_uniprot,ident_salmo
0,TRINITY_DN100000_c5_g1_i6,683,674,487,685,654,492,604.304316,-0.179745,0.304724,-0.589861,0.555284,0.999996,CAPON_MOUSE,XP_013978521.1
1,TRINITY_DN100000_c9_g1_i1,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,CH049_HUMAN,NaN
2,TRINITY_DN100001_c2_g2_i2,1190,1280,1223,1034,1012,1252,1145.939552,-0.035965,0.256702,-0.140103,0.888579,0.999996,CIO1B_SALSA,XP_014027367.1
3,TRINITY_DN100001_c2_g2_i7,451,464,516,377,338,305,398.258863,0.292943,0.267341,1.095766,0.273181,0.999996,CIO1B_SALSA,XP_014015694.1^XP_014027367.1
4,TRINITY_DN100001_c2_g3_i3,547,568,579,522,338,320,466.619820,0.327023,0.311017,1.051464,0.293046,0.999996,CIO1B_SALSA,XP_014027367.1

In [13]:
merged.to_csv(path+'1d_MIS_vs_INH_DESEQ_annotated.csv', index=False)

In [14]:
# sorting annotated deseq results (padj < 0.001, l2fc sorted)

In [2]:
path="/mnt/sdb1/Project_Sieja_MCLR_52/2_pipeline/7_counting_transcripts/proteins_uniprot_salmo_brzuzan/"

In [3]:
deseq_annotated = pd.read_csv(path+'1d_MIS_vs_PBS_DESEQ_annotated.csv', low_memory=False)
deseq_annotated.head()

,trinity,ident_uniprot,ident_salmo,MIS_1d_1,MIS_1d_2,MIS_1d_3,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,TRINITY_DN100000_c5_g1_i6,CAPON_MOUSE,XP_013978521.1,683,674,487,374,506,607,594,552.394985,-0.112483,0.302897,-0.371358,0.710371,0.999999
1,TRINITY_DN100000_c9_g1_i1,CH049_HUMAN,NaN,0,0,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN
2,TRINITY_DN100001_c2_g2_i2,CIO1B_SALSA,XP_014027367.1,1190,1280,1223,1232,1264,998,1041,1151.562119,-0.001951,0.183114,-0.010652,0.991501,0.999999
3,TRINITY_DN100001_c2_g2_i7,CIO1B_SALSA,XP_014015694.1^XP_014027367.1,451,464,516,562,408,311,353,427.400196,-0.112900,0.262494,-0.430104,0.667120,0.999999
4,TRINITY_DN100001_c2_g3_i3,CIO1B_SALSA,XP_014027367.1,547,568,579,565,525,384,405,498.524237,-0.152371,0.223010,-0.683247,0.494451,0.999999

In [4]:
deseq_annotated_padj = deseq_annotated[deseq_annotated['padj'] < 0.001]

In [5]:
deseq_annotated_sorted = deseq_annotated_padj.sort_values(by='log2FoldChange')

In [6]:
deseq_annotated_sorted.head()

,trinity,ident_uniprot,ident_salmo,MIS_1d_1,MIS_1d_2,MIS_1d_3,PBS_1d_1,PBS_1d_2,PBS_1d_3,PBS_1d_4,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
86171,TRINITY_DN81112_c0_g2_i1,CTRB_GADMO,NP_001134565.1,63,1619,190,0,0,0,0,241.086370,-11.553876,2.159652,-5.349878,8.801342e-08,1.413412e-04
98277,TRINITY_DN87385_c2_g1_i9,CTRL_HUMAN,NP_001135026.1,56,726,120,0,0,0,0,116.639490,-10.506454,1.895065,-5.544114,2.954471e-08,6.227285e-05
26132,TRINITY_DN109898_c8_g6_i1,LWA_HYDEC,XP_014039776.1,282,328,160,0,0,0,0,103.038405,-10.327484,1.108850,-9.313694,1.234625e-20,1.784422e-16
79615,TRINITY_DN73718_c0_g1_i2,AGRL1_MOUSE,XP_014040079.1,231,282,159,0,0,0,0,89.799932,-10.129142,1.098556,-9.220413,2.959578e-20,3.639757e-16
79614,TRINITY_DN73718_c0_g1_i1,AGRL1_MOUSE,XP_014040079.1,252,317,152,0,1,0,0,96.464105,-9.508998,1.106850,-8.591047,8.618047e-18,6.706962e-14

In [7]:
deseq_annotated_sorted.to_csv(path+"1d_MIS_vs_PBS_DESEQ_annotated_padj0001_l2fc_sorted.csv", index=False)

In [8]:
# sorting annotated deseq_results (padj sorted)

In [5]:
deseq_annotated = pd.read_csv(path+'1d_MIS_vs_INH_DESEQ_annotated.csv', low_memory=False)
deseq_annotated_sorted = deseq_annotated.sort_values(by='padj')
deseq_annotated_sorted.to_csv(path+"1d_MIS_vs_INH_DESEQ_annotated_padj_sorted.csv", index=False)